(()=>{
const boardEl=document.querySelector('#board'),statusEl=document.querySelector('#status'),whiteScore=document.querySelector('#whiteScore'),blackScore=document.querySelector('#blackScore');
const symbols={K:'♔',Q:'♕',R:'♖',B:'♗',N:'♘',P:'♙',k:'♚',q:'♛',r:'♜',b:'♝',n:'♞',p:'♟'};
let board,turn,selected,lastMove,castle,enPassant,finished=false;
const inside=(r,c)=>r>=0&&r<8&&c>=0&&c<8,color=p=>p?(p===p.toUpperCase()?'w':'b'):null,enemy=(p,side)=>p&&color(p)!==side;
function initial(){return['rnbqkbnr','pppppppp','........','........','........','........','PPPPPPPP','RNBQKBNR'].map(row=>[...row].map(p=>p==='.'?'':p))}
function reset(emit=true){board=initial();turn='w';selected=null;lastMove=null;castle={wK:true,wQ:true,bK:true,bQ:true};enPassant=null;finished=false;render();if(emit)broadcast()}
function clone(value){return value.map(row=>[...row])}
function attacked(b,r,c,by){const pawn=by==='w'?-1:1;for(const dc of[-1,1]){const rr=r-pawn,cc=c-dc;if(inside(rr,cc)&&b[rr][cc]===(by==='w'?'P':'p'))return true}for(const[dr,dc]of[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]]){const rr=r+dr,cc=c+dc;if(inside(rr,cc)&&b[rr][cc]===(by==='w'?'N':'n'))return true}for(const[dr,dc,types]of[[1,0,'RQ'],[-1,0,'RQ'],[0,1,'RQ'],[0,-1,'RQ'],[1,1,'BQ'],[1,-1,'BQ'],[-1,1,'BQ'],[-1,-1,'BQ']]){let rr=r+dr,cc=c+dc;while(inside(rr,cc)){if(b[rr][cc]){if(color(b[rr][cc])===by&&types.includes(b[rr][cc].toUpperCase()))return true;break}rr+=dr;cc+=dc}}for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc){const rr=r+dr,cc=c+dc;if(inside(rr,cc)&&b[rr][cc]===(by==='w'?'K':'k'))return true}return false}
function inCheck(b,side){for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(b[r][c]===(side==='w'?'K':'k'))return attacked(b,r,c,side==='w'?'b':'w');return true}
function pseudo(r,c,b=board,includeCastle=true){const p=b[r][c],side=color(p),type=p?.toUpperCase(),moves=[],add=(rr,cc,special)=>{if(inside(rr,cc)&&(!b[rr][cc]||enemy(b[rr][cc],side)))moves.push({r:rr,c:cc,special})};if(!p)return moves;
if(type==='P'){const d=side==='w'?-1:1,start=side==='w'?6:1;if(inside(r+d,c)&&!b[r+d][c]){moves.push({r:r+d,c});if(r===start&&!b[r+2*d][c])moves.push({r:r+2*d,c,special:'double'})}for(const dc of[-1,1]){const rr=r+d,cc=c+dc;if(inside(rr,cc)&&enemy(b[rr][cc],side))moves.push({r:rr,c:cc});if(enPassant&&enPassant.r===rr&&enPassant.c===cc)moves.push({r:rr,c:cc,special:'ep'})}}
if(type==='N')for(const[dr,dc]of[[-2,-1],[-2,1],[-1,-2],[-1,2],[1,-2],[1,2],[2,-1],[2,1]])add(r+dr,c+dc);
if('RBQ'.includes(type)){const dirs=type==='R'?[[1,0],[-1,0],[0,1],[0,-1]]:type==='B'?[[1,1],[1,-1],[-1,1],[-1,-1]]:[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];for(const[dr,dc]of dirs){let rr=r+dr,cc=c+dc;while(inside(rr,cc)){if(!b[rr][cc])moves.push({r:rr,c:cc});else{if(enemy(b[rr][cc],side))moves.push({r:rr,c:cc});break}rr+=dr;cc+=dc}}}
if(type==='K'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);if(includeCastle&&!inCheck(b,side)){const home=side==='w'?7:0,foe=side==='w'?'b':'w';if(r===home&&c===4){if(castle[side+'K']&&!b[home][5]&&!b[home][6]&&b[home][7]===(side==='w'?'R':'r')&&!attacked(b,home,5,foe)&&!attacked(b,home,6,foe))moves.push({r:home,c:6,special:'castleK'});if(castle[side+'Q']&&!b[home][1]&&!b[home][2]&&!b[home][3]&&b[home][0]===(side==='w'?'R':'r')&&!attacked(b,home,3,foe)&&!attacked(b,home,2,foe))moves.push({r:home,c:2,special:'castleQ'})}}return moves}
return moves}
function simulate(r,c,m){const b=clone(board),p=b[r][c];b[m.r][m.c]=p;b[r][c]='';if(m.special==='ep')b[r][m.c]='';if(m.special==='castleK'){b[m.r][5]=b[m.r][7];b[m.r][7]=''}if(m.special==='castleQ'){b[m.r][3]=b[m.r][0];b[m.r][0]=''}return b}
function legal(r,c){if(color(board[r][c])!==turn)return[];return pseudo(r,c).filter(m=>!inCheck(simulate(r,c,m),turn))}
function allMoves(side){const result=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(color(board[r][c])===side)for(const m of legalFor(side,r,c))result.push({from:{r,c},to:m});return result}function legalFor(side,r,c){const old=turn;turn=side;const result=legal(r,c);turn=old;return result}
function move(r,c,m){const p=board[r][c],side=color(p),type=p.toUpperCase();if(type==='K'){castle[side+'K']=castle[side+'Q']=false}if(type==='R'){if(r===7&&c===0)castle.wQ=false;if(r===7&&c===7)castle.wK=false;if(r===0&&c===0)castle.bQ=false;if(r===0&&c===7)castle.bK=false}if(board[m.r][m.c]?.toUpperCase()==='R'){if(m.r===7&&m.c===0)castle.wQ=false;if(m.r===7&&m.c===7)castle.wK=false;if(m.r===0&&m.c===0)castle.bQ=false;if(m.r===0&&m.c===7)castle.bK=false}board=simulate(r,c,m);if(type==='P'&&(m.r===0||m.r===7))board[m.r][m.c]=side==='w'?'Q':'q';enPassant=m.special==='double'?{r:(r+m.r)/2,c}:null;lastMove={from:{r,c},to:{r:m.r,c:m.c}};turn=turn==='w'?'b':'w';selected=null;const moves=allMoves(turn);finished=!moves.length;render();broadcast()}
function click(r,c){if(finished)return;const player=window.ILPlayerSide;if(player&&player!==turn){statusEl.textContent=`Aguarde a vez das peças ${player==='w'?'brancas':'pretas'}`;return}if(selected){const found=legal(selected.r,selected.c).find(m=>m.r===r&&m.c===c);if(found){move(selected.r,selected.c,found);return}}selected=color(board[r][c])===turn?{r,c}:null;render()}
function render(){boardEl.innerHTML='';let whites=0,blacks=0;const targets=selected?legal(selected.r,selected.c):[];for(let r=0;r<8;r++)for(let c=0;c<8;c++){const cell=document.createElement('button');cell.className='cell '+((r+c)%2?'dark':'');cell.setAttribute('aria-label',`linha ${r+1}, coluna ${c+1}`);if(selected?.r===r&&selected?.c===c)cell.classList.add('selected');if(targets.some(m=>m.r===r&&m.c===c))cell.classList.add('target');if(lastMove&&(lastMove.from.r===r&&lastMove.from.c===c||lastMove.to.r===r&&lastMove.to.c===c))cell.classList.add('last-move');const p=board[r][c];if(p){color(p)==='w'?whites++:blacks++;const piece=document.createElement('span');piece.className='chess-piece '+(color(p)==='w'?'white':'black');piece.textContent=symbols[p];cell.append(piece);if(p.toUpperCase()==='K'&&inCheck(board,color(p)))cell.classList.add('in-check')}cell.onclick=()=>click(r,c);boardEl.append(cell)}whiteScore.textContent=whites;blackScore.textContent=blacks;const checked=inCheck(board,turn);if(finished)statusEl.textContent=checked?`Xeque-mate! ${turn==='w'?'Pretas':'Brancas'} venceram`:'Empate por afogamento';else statusEl.textContent=(checked?'Xeque — ':'')+`Vez das peças ${turn==='w'?'brancas':'pretas'}`}
function snapshot(){return{board,turn,lastMove,castle,enPassant,finished}}function apply(data){if(!data?.board||!Array.isArray(data.board))return;board=clone(data.board);turn=data.turn;lastMove=data.lastMove;castle=data.castle;enPassant=data.enPassant;finished=!!data.finished;selected=null;render()}function broadcast(){window.dispatchEvent(new CustomEvent('il-game-change',{detail:snapshot()}))}document.querySelector('#newGame').onclick=()=>{if(window.ILPlayerSide==='b'){statusEl.textContent='Somente quem criou a sala inicia uma nova partida';return}reset()};window.ILGame={snapshot,apply,reset};reset(false);
})();
