(()=>{
const boardEl=document.querySelector('#board'),statusEl=document.querySelector('#status'),dot=document.querySelector('#turnDot'),blueEl=document.querySelector('#blueScore'),pinkEl=document.querySelector('#pinkScore');
let board,turn,selected,targets,chain=false;
const inside=(r,c)=>r>=0&&r<8&&c>=0&&c<8;
const dirs=[[-1,-1],[-1,1],[1,-1],[1,1]];
function emit(){window.dispatchEvent(new CustomEvent('il-game-change',{detail:snapshot()}))}
function snapshot(){return{board:board.map(row=>row.map(p=>p?{...p}:null)),turn}}
function apply(data){if(!data?.board||!data?.turn)return;board=data.board;turn=data.turn;selected=null;targets=[];chain=false;render()}
function reset(sync=true){board=Array.from({length:8},()=>Array(8).fill(null));for(let r=0;r<3;r++)for(let c=0;c<8;c++)if((r+c)%2)board[r][c]={color:'blue',king:false};for(let r=5;r<8;r++)for(let c=0;c<8;c++)if((r+c)%2)board[r][c]={color:'pink',king:false};turn='blue';selected=null;targets=[];chain=false;render();if(sync)emit()}
function normalMoves(r,c){const p=board[r][c],out=[];if(!p)return out;if(p.king){for(const[dr,dc]of dirs){let nr=r+dr,nc=c+dc;while(inside(nr,nc)&&!board[nr][nc]){out.push({r:nr,c:nc});nr+=dr;nc+=dc}}return out}const forward=p.color==='blue'?1:-1;for(const dc of[-1,1]){const nr=r+forward,nc=c+dc;if(inside(nr,nc)&&!board[nr][nc])out.push({r:nr,c:nc})}return out}
function captureMoves(r,c){const p=board[r][c],out=[];if(!p)return out;if(p.king){for(const[dr,dc]of dirs){let nr=r+dr,nc=c+dc,enemy=null;while(inside(nr,nc)){const square=board[nr][nc];if(!square){if(enemy)out.push({r:nr,c:nc,capture:enemy});nr+=dr;nc+=dc;continue}if(square.color===p.color||enemy)break;enemy=[nr,nc];nr+=dr;nc+=dc}}return out}const forward=p.color==='blue'?1:-1;for(const dc of[-1,1]){const er=r+forward,ec=c+dc,lr=r+forward*2,lc=c+dc*2;if(inside(lr,lc)&&board[er]?.[ec]&&board[er][ec].color!==p.color&&!board[lr][lc])out.push({r:lr,c:lc,capture:[er,ec]})}return out}
function hasCapture(color){for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(board[r][c]?.color===color&&captureMoves(r,c).length)return true;return false}
function choose(r,c){const target=targets.find(x=>x.r===r&&x.c===c);if(target&&selected){const p=board[selected.r][selected.c];board[r][c]=p;board[selected.r][selected.c]=null;if(target.capture){board[target.capture[0]][target.capture[1]]=null;if((p.color==='blue'&&r===7)||(p.color==='pink'&&r===0))p.king=true;const more=captureMoves(r,c);if(more.length){selected={r,c};targets=more;chain=true;render();emit();return}}else if((p.color==='blue'&&r===7)||(p.color==='pink'&&r===0))p.king=true;turn=turn==='blue'?'pink':'blue';selected=null;targets=[];chain=false;render();emit();return}
if(chain)return;const p=board[r][c];if(p&&p.color===turn){const forced=hasCapture(turn);const options=forced?captureMoves(r,c):normalMoves(r,c);if(options.length){selected={r,c};targets=options}else{selected=null;targets=[]}}else{selected=null;targets=[]}render()}
function render(){boardEl.innerHTML='';for(let r=0;r<8;r++)for(let c=0;c<8;c++){const cell=document.createElement('button');cell.className='cell '+((r+c)%2?'dark':'');cell.setAttribute('aria-label',`linha ${r+1}, coluna ${c+1}`);if(selected&&selected.r===r&&selected.c===c)cell.classList.add('selected');if(targets.some(x=>x.r===r&&x.c===c))cell.classList.add('target');const p=board[r][c];if(p){const piece=document.createElement('span');piece.className=`piece ${p.color==='pink'?'pink':''} ${p.king?'king':''}`;cell.append(piece)}cell.onclick=()=>choose(r,c);boardEl.append(cell)}const blue=board.flat().filter(x=>x?.color==='blue').length,pink=board.flat().filter(x=>x?.color==='pink').length;blueEl.textContent=blue;pinkEl.textContent=pink;statusEl.textContent=!blue?'Rosas venceram!':!pink?'Azuis venceram!':chain?'Continue capturando com a mesma peça':hasCapture(turn)?`Vez das ${turn==='blue'?'azuis':'rosas'} — captura obrigatória`:`Vez das peças ${turn==='blue'?'azuis':'rosas'}`;const color=turn==='blue'?'#20dafa':'#ef3d94';dot.style.background=color;dot.style.boxShadow=`0 0 16px ${color}`}
document.querySelector('#newGame').onclick=()=>reset();window.ILGame={snapshot,apply,reset};reset(false)
})();
