(()=>{
const $=s=>document.querySelector(s),state=$('#roomState'),messages=$('#chatMessages'),text=$('#chatText'),send=$('#chatSend'),photo=$('#chatPhoto'),photoButton=$('#photoButton'),voice=$('#voiceCall'),video=$('#videoCall'),copy=$('#copyInvite'),report=$('#reportUser'),block=$('#blockUser'),kick=$('#kickUser');let peer,connection,room='',stream,currentCall,isHost=false,blocked=false;const photoParts=new Map,random=()=>Math.random().toString(36).slice(2,8).toUpperCase();
function notice(v){const p=document.createElement('p');p.className='notice';p.textContent=v;messages.append(p);messages.scrollTop=messages.scrollHeight}function message(v,mine){const p=document.createElement('p');if(mine)p.className='mine';p.textContent=v;messages.append(p);messages.scrollTop=messages.scrollHeight}function image(src,mine){const p=document.createElement('p');if(mine)p.className='mine';const img=document.createElement('img');img.src=src;img.alt='Foto compartilhada';p.append(img);messages.append(p);messages.scrollTop=messages.scrollHeight}
function acceptedRules(){if(sessionStorage.getItem('il-games-adult-rules')==='yes')return true;const ok=confirm('SALA SOCIAL PARA MAIORES DE 18 ANOS\n\nÉ proibido conteúdo sexual sem consentimento, assédio, ameaças e qualquer exposição envolvendo menores. Câmera e microfone só funcionam com autorização.\n\nVocê tem 18 anos ou mais e aceita as regras?');if(ok)sessionStorage.setItem('il-games-adult-rules','yes');return ok}function enable(ok){text.disabled=send.disabled=photo.disabled=voice.disabled=video.disabled=report.disabled=block.disabled=!ok;kick.disabled=!ok;kick.hidden=!isHost}function transmit(data){if(connection?.open)connection.send(data)}
function endCall(){const call=currentCall,current=stream;currentCall=stream=null;current?.getTracks().forEach(t=>t.stop());if(call?.open)call.close();$('#videoStage').hidden=true;$('#remoteVideo').srcObject=$('#mineVideo').srcObject=$('#remoteAudio').srcObject=null}function disconnect(reason='Você saiu da sala.'){endCall();connection?.close();peer?.destroy();connection=peer=null;enable(false);state.textContent=reason}
function receivePhoto(data){let entry=photoParts.get(data.id);if(!entry){entry={parts:new Array(data.total),received:0};photoParts.set(data.id,entry)}if(entry.parts[data.index]===undefined){entry.parts[data.index]=data.value;entry.received++}if(entry.received===data.total){image(entry.parts.join(''),false);notice('Foto recebida.');photoParts.delete(data.id)}}function sendPhoto(data){const id=random()+Date.now(),size=12000,total=Math.ceil(data.length/size);for(let index=0;index<total;index++)transmit({type:'photo-part',id,index,total,value:data.slice(index*size,(index+1)*size)})}
function bind(conn){if(blocked){conn.close();return}connection=conn;conn.on('open',()=>{state.textContent=`Conectado na sala ${room}.`;enable(true);notice('A outra pessoa entrou. Vocês já podem conversar e jogar.');if(window.ILGame)transmit({type:'game',value:window.ILGame.snapshot()})});conn.on('data',data=>{if(data.type==='text')message(data.value,false);if(data.type==='photo')image(data.value,false);if(data.type==='photo-part')receivePhoto(data);if(data.type==='game'&&window.ILGame)window.ILGame.apply(data.value);if(data.type==='kick'){alert('O criador encerrou sua participação nesta sala.');disconnect('Você foi retirado desta sala.')}});conn.on('close',()=>{if(connection===conn){state.textContent='A outra pessoa saiu da sala.';enable(false)}})}
function startPeer(id,ready){peer?.destroy();peer=new Peer(id,{debug:1});peer.on('open',ready);peer.on('connection',bind);peer.on('call',call=>{const wantsVideo=!!call.metadata?.video,kind=wantsVideo?'videochamada':'chamada de voz';if(!confirm(`A outra pessoa está fazendo uma ${kind}. Deseja atender?`)){call.close();notice(`${kind} recusada.`);return}answerCall(call,wantsVideo)});peer.on('error',()=>state.textContent='Não foi possível conectar. Crie outra sala e tente novamente.')}
$('.create-room').onclick=()=>{if(!acceptedRules())return;isHost=true;blocked=false;room=random();$('#roomCode').value=room;state.textContent='Criando sala…';startPeer('il-jogos-'+room,()=>{state.textContent=`Sala ${room} criada. Copie o convite.`;copy.hidden=false;kick.hidden=false})};$('.join-room').onclick=()=>{if(!acceptedRules())return;isHost=false;blocked=false;room=$('#roomCode').value.trim().toUpperCase();if(room.length<4){state.textContent='Digite o código da sala.';return}state.textContent='Entrando na sala…';startPeer('il-visitante-'+random(),()=>bind(peer.connect('il-jogos-'+room,{reliable:true})))};copy.onclick=async()=>{const url=`${location.origin}${location.pathname}?sala=${room}`;await navigator.clipboard.writeText(url);state.textContent='Convite copiado. Envie para a outra pessoa.'};
function openPhonePhoto(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image;img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject()};img.src=url})}async function decodePhoto(file){try{return await createImageBitmap(file)}catch{return openPhonePhoto(file)}}
$('#chatForm').onsubmit=e=>{e.preventDefault();const v=text.value.trim();if(!v)return;message(v,true);transmit({type:'text',value:v});text.value=''};photo.onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>20*1024*1024){notice('Escolha uma foto com até 20 MB.');return}notice('Preparando a foto…');try{const bitmap=await decodePhoto(file),scale=Math.min(1,900/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();const data=canvas.toDataURL('image/jpeg',.7);image(data,true);sendPhoto(data);notice('Foto enviada.')}catch{notice('Este formato de foto não pôde ser aberto. Tente uma foto JPG ou PNG.')}};
async function media(withVideo){return navigator.mediaDevices.getUserMedia({audio:true,video:withVideo})}async function answerCall(call,withVideo){try{stream=await media(withVideo);call.answer(stream);showCall(call,withVideo)}catch{call.close();notice('Não foi possível abrir o microfone ou a câmera.')}}async function makeCall(withVideo){try{stream=await media(withVideo);currentCall=peer.call(connection.peer,stream,{metadata:{video:withVideo}});showCall(currentCall,withVideo)}catch{notice('Permita o microfone e a câmera para fazer a chamada.')}}function showCall(call,withVideo){currentCall=call;if(withVideo){$('#videoStage').hidden=false;$('#mineVideo').srcObject=stream}call.on('stream',remote=>{if(withVideo)$('#remoteVideo').srcObject=remote;else{$('#remoteAudio').srcObject=remote;notice('Chamada de voz conectada.')}});call.on('close',endCall)}
report.onclick=()=>{const reason=prompt('Descreva brevemente o motivo da denúncia:');if(!reason?.trim())return;const reports=JSON.parse(localStorage.getItem('il-games-reports')||'[]');reports.push({room,date:new Date().toISOString(),reason:reason.trim()});localStorage.setItem('il-games-reports',JSON.stringify(reports));alert('Registro salvo neste aparelho. Se houver perigo, bloqueie e saia.');notice('Ocorrência registrada neste aparelho.')};block.onclick=()=>{if(confirm('Bloquear esta pessoa e sair da sala agora?')){blocked=true;disconnect('Pessoa bloqueada. Você saiu da sala.')}};kick.onclick=()=>{if(isHost&&confirm('Expulsar esta pessoa da sala?')){transmit({type:'kick'});setTimeout(()=>disconnect('Pessoa expulsa. Sala encerrada.'),200)}};
voice.onclick=()=>makeCall(false);video.onclick=()=>makeCall(true);$('#endCall').onclick=endCall;window.addEventListener('il-game-change',e=>transmit({type:'game',value:e.detail}));const invited=new URLSearchParams(location.search).get('sala');if(invited){$('#roomCode').value=invited.toUpperCase();state.textContent='Convite recebido. Toque em Entrar.'}
})();
